baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'flatpancakesss.dev'
theme = 'nostyleplease' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true